### ISSUE TITLE
Wifi MAC management / change support? [question] 

### ISSUE THREAD

**Issue by tonsimple** [FireLord/android_kernel_lenovo_msm8953#3]
Hello!

I am considering Lenovo P2 as a future phone, and I plan on using Lineage OS however, I have a certain special need.

Thing is, I might need to change MAC address, ideally without using the PC (so constantly tampering with NV items via QPST is not appealing).

So, long story short, it was pointed out to me that LineageOS for msm8953 might have functionality like that, and the following file has been pointed as evidence

https://github.com/Wzedlare/android_device_lenovo_p2a42/blob/cm-14.1/wifi/WCNSS_qcom_cfg.ini

the parameter gEnableMacAddrSpoof suggests that something like what I want should be possible.

However, in your WCNSS_qcom_cfg.ini found here

https://github.com/FireLord1/android_kernel_lenovo_msm8953/blob/cm-14.1/drivers/staging/prima/firmware_bin/WCNSS_qcom_cfg.ini

there is no such parameter.

Thus, question:
Is ability to change MAC on the fly possible on Lenovo P2, and if so, how would one go about actually doing so?

**Comment by FireLord1** [comment]
actually i dont know.. the config which i have is not from stock rom.. its from caf thats why its diff.. ill try stock config once

**Comment by tonsimple** [comment]
@FireLord1 Thanks!
If it isn't too much trouble, could you test MAC change/spoof functionality specifically when you try that config?
